name: sagaeat_business
description: "SagaEat Business — Logiciel SaaS pour Restaurants & Fast Food"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  print_bluetooth_thermal: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.2
  flutter_native_splash: ^2.4.5

dependency_overrides:
  material_color_utilities: '>=0.11.1 <0.14.0'
  meta: '>=1.17.0 <2.0.0'
  characters: '>=1.4.0 <2.0.0'
  matcher: '>=0.12.17 <0.13.0'
  test_api: '>=0.7.7 <0.8.0'

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21
  windows:
    generate: true
    image_path: "assets/images/icon.png"
    icon_size: 256
  macos:
    generate: true
    image_path: "assets/images/icon.png"

flutter_native_splash:
  color: "#EF6C00"
  image: assets/images/splash.png
  color_dark: "#EF6C00"
  image_dark: assets/images/splash.png
  android_12:
    color: "#EF6C00"
    image: assets/images/icon.png
    icon_background_color: "#EF6C00"
  fullscreen: true
  web: false
